apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: interview-ai
  labels:
    app: api-service
spec:
  ports:
    - port: 8001
      targetPort: 8001
      name: http
  selector:
    app: api-service
