apiVersion: v1
kind: Service
metadata:
  name: question-service
  namespace: interview-ai
  labels:
    app: question-service
spec:
  selector:
    app: question-service
  ports:
    - port: 8000
      targetPort: 8000
      name: http
